'use strict';
const MAX_YEARS=40;
const defaults={name:'',address:'',price:389000,land:130000,units:1,rent:3700,rentGrowth:.02,vacancy:.10,opEx:.40,depLife:27.5,appreciation:.03,hold:7,sellCost:.05,mortgage:0,interestOnly:true,mortRate:0,loanYears:7,points:0,origFee:0,ordinaryTax:.28,depTax:.25,capGainsTax:.15,requiredReturn:.10,desiredCap:.065,desiredGrm:8.35};
const buydownDefaults={loan1Amount:200000,loan1Years:30,loan1Rate:.07,loan2Rate:.063,loan2Points:2};
let state={...defaults},buyState={...buydownDefaults},result=null,scenarioState={B:{mortgage:311200,mortRate:.065,loanYears:30,interestOnly:false,points:0,origFee:0},C:{mortgage:0,mortRate:0,loanYears:30,interestOnly:false,points:0,origFee:0}};
const fg={propertyFields:[['price','Acquisition Price','$'],['land','Land Value','$'],['units','# of Apartments','n'],['rent','Rent per Month','$'],['rentGrowth','Rent Increase Starting in Year 2','%'],['vacancy','Vacancy and Credit Losses','%'],['opEx','Other Operating Expenses as % of EGI','%'],['depLife','Depreciable Life in Years','n'],['appreciation','Annual Property Value Increase','%'],['hold','Expected Holding Period','n'],['sellCost','Selling Expenses','%']],financeFields:[['mortgage','Mortgage Amount','$'],['interestOnly','Interest Only','b'],['mortRate','Mortgage Rate','%'],['loanYears','Mortgage Time Horizon','n'],['points','Mortgage Points','n'],['origFee','Origination Fee','$']],taxFields:[['ordinaryTax','Ordinary Income Tax Rate','%'],['depTax','Depreciation Tax Rate','%'],['capGainsTax','Capital Gains Tax Rate','%'],['requiredReturn','Required Rate of Return','%']],valuationFields:[['desiredCap','Desired Capitalization Rate','%'],['desiredGrm','Desired Gross Rent Multiplier','n']]};
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d,clamp=(x,a,b)=>Math.min(b,Math.max(a,x));
const fmtC=(v,d=0)=>Number.isFinite(v)?(v<0?'(':'')+Math.abs(v).toLocaleString('en-US',{style:'currency',currency:'USD',minimumFractionDigits:d,maximumFractionDigits:d})+(v<0?')':''):'N/A';
const fmtP=(v,d=2)=>Number.isFinite(v)?(v*100).toFixed(d)+'%':'N/A',fmtX=(v,d=2)=>Number.isFinite(v)?v.toFixed(d)+'x':'N/A';

// Standard payment helper retained only for the non-proprietary rate-buydown UI.
const pmt=(r,m,p)=>m?(r?r*p/(1-Math.pow(1+r,-m)):p/m):0;
// Proprietary investment-return calculations are no longer implemented in browser code.
const npv=()=>{throw new Error('Protected calculation engine required');};
function irr(){throw new Error('Protected calculation engine required');}
function analyze(){throw new Error('Protected calculation engine result is not ready');}

function renderFields(){for(const [id,fields] of Object.entries(fg)){const h=document.getElementById(id);if(!h)continue;h.innerHTML='';for(const [k,l,t]of fields){const val=t==='%'?state[k]*100:state[k];h.insertAdjacentHTML('beforeend',`<div class="field"><label>${l}</label>${t==='b'?`<select id="f_${k}"><option value="true">YES</option><option value="false">NO</option></select>`:`<input id="f_${k}" type="number" value="${val}" step="${t==='%'?.01:t==='$'?100:1}">`}</div>`);if(t==='b'){const el=document.getElementById('f_'+k);if(el)el.value=String(state[k]);}}}const nm=document.getElementById('f_name'),ad=document.getElementById('f_address');if(nm)nm.value=state.name;if(ad)ad.value=state.address;syncQuick();renderBuydownFields();}
function readFields(){for(const fields of Object.values(fg))for(const[k,,t]of fields){const e=document.getElementById('f_'+k);if(!e)continue;state[k]=t==='b'?e.value==='true':n(e.value,state[k])/(t==='%'?100:1);}const nm=document.getElementById('f_name'),ad=document.getElementById('f_address');if(nm)state.name=nm.value.trim();if(ad)state.address=ad.value.trim();state.hold=clamp(Math.round(state.hold),1,40);state.loanYears=clamp(Math.round(state.loanYears),1,40);state.units=Math.max(1,Math.round(state.units));state.land=clamp(state.land,0,state.price);syncQuick();}
function syncQuick(){const a=document.getElementById('propertyName'),b=document.getElementById('quickPrice'),c=document.getElementById('quickRent'),d=document.getElementById('printTitle');if(a)a.value=state.name;if(b)b.value=state.price;if(c)c.value=state.rent;if(d)d.textContent=state.name||'Investment Property Analysis';}
const metric=(l,v)=>`<div>${l}</div><div>${v}</div>`,cell=(text,raw)=>({text,raw});
function tableHTML(headers,rows){return `<thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.cells.map(c=>`<td>${c.text}</td>`).join('')}</tr>`).join('')}</tbody>`;}

function render(){
  result=analyze(state);
  if(!result?.years?.length)return;
  const y=result.years[0],eq=-result.initial,coc=eq?y.atcf/eq:NaN;
  const set=(id,html)=>{const el=document.getElementById(id);if(el)el.innerHTML=html;};
  set('kpis',[['Year 1 Cap Rate',fmtP(result.cap)],['Year 1 GRM',fmtX(result.grm)],['IRR',fmtP(result.IRR)],['NPV',fmtC(result.NPV)],['Year 1 Cash-on-Cash',fmtP(coc)],['Year 1 DSCR',fmtX(y.dcr)]].map(x=>`<div class="kpi"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join(''));
  set('snapshot',metric('Purchase Price',fmtC(state.price))+metric('Monthly Rent',fmtC(state.rent))+metric('Year 1 NOI',fmtC(y.noi))+metric('Initial Equity',fmtC(eq)));
  set('valuation',metric('Direct Cap Value',fmtC(result.capValue))+metric('GRM Value',fmtC(result.grmValue)));
  set('financing',metric('Mortgage',fmtC(state.mortgage))+metric('Monthly Payment',fmtC(result.monthlyPayment,2))+metric('Year 1 DSCR',fmtX(y.dcr)));
  set('saleSummary',metric('Gross Sale Price',fmtC(result.grossSale))+metric('Taxes Due on Sale',fmtC(result.saleTax))+metric('After-Tax Reversion',fmtC(result.ater)));
  set('returnSummary',metric('Required Return',fmtP(state.requiredReturn))+metric('IRR',fmtP(result.IRR))+metric('NPV',fmtC(result.NPV)));
  set('modelHealth',`<div class="note">${result.NPV>=0?'Model meets the selected required return.':'Model falls below the selected required return.'}</div>`);
  renderTables();renderScenarios();renderSupport();renderClientReport();refreshLibrary();
}
function renderTables(){if(!result?.years)return;const yrs=result.years,set=(id,html)=>{const el=document.getElementById(id);if(el)el.innerHTML=html;};set('cashflowTable',tableHTML(['Year','PGI','EGI','NOI','Debt','Tax','After-Tax CF'],yrs.map(y=>({cells:[cell(y.year),cell(fmtC(y.pgi)),cell(fmtC(y.egi)),cell(fmtC(y.noi)),cell(fmtC(y.debt)),cell(fmtC(y.opTax)),cell(fmtC(y.atcf))]}))));set('totalCfTable',tableHTML(['Year','Total Investment CF'],(result.cfs||[]).map((v,i)=>({cells:[cell(i),cell(fmtC(v))]}))));set('reversionTable',tableHTML(['Item','Amount'],[['Gross Sale',result.grossSale],['Selling Costs',-result.selling],['Loan Payoff',-result.loanPayoff],['Sale Taxes',-result.saleTax],['After-Tax Reversion',result.ater]].map(x=>({cells:[cell(x[0]),cell(fmtC(x[1]))]}))));set('debtTable',tableHTML(['Year','Debt Service','Interest','Principal','Ending Balance','DSCR'],yrs.map(y=>({cells:[cell(y.year),cell(fmtC(y.debt)),cell(fmtC(y.interest)),cell(fmtC(y.principal)),cell(fmtC(y.endBalance)),cell(fmtX(y.dcr))]}))));set('opTaxTable',tableHTML(['Year','Taxable Income','Operating Tax'],yrs.map(y=>({cells:[cell(y.year),cell(fmtC(y.taxable)),cell(fmtC(y.opTax))]}))));set('saleTaxTable',tableHTML(['Item','Amount'],[['Accumulated Depreciation',result.accDep],['Book Value',result.book],['Gain',result.gain],['Taxes Due on Sale',result.saleTax]].map(x=>({cells:[cell(x[0]),cell(fmtC(x[1]))]}))));set('amortTable',tableHTML(['Year','Month','Payment','Interest','Principal','Balance'],(result.amort||[]).map(a=>({cells:[cell(a.year),cell(a.month),cell(fmtC(a.payment,2)),cell(fmtC(a.interest,2)),cell(fmtC(a.principal,2)),cell(fmtC(a.balance,2))]}))));}

function renderBuydownFields(){const one=document.getElementById('buydownOne'),two=document.getElementById('buydownTwo');if(one)one.innerHTML=`<div class="field"><label>Loan Amount</label><input id="b_amount" type="number" value="${buyState.loan1Amount}"></div><div class="field"><label>Years</label><input id="b_years" type="number" value="${buyState.loan1Years}"></div><div class="field"><label>Rate</label><input id="b_rate1" type="number" value="${buyState.loan1Rate*100}"></div>`;if(two)two.innerHTML=`<div class="field"><label>Rate With Points</label><input id="b_rate2" type="number" value="${buyState.loan2Rate*100}"></div><div class="field"><label>Points</label><input id="b_points" type="number" value="${buyState.loan2Points}"></div>`;renderBuydown();}
function readBuydown(){buyState={loan1Amount:n(document.getElementById('b_amount')?.value),loan1Years:n(document.getElementById('b_years')?.value),loan1Rate:n(document.getElementById('b_rate1')?.value)/100,loan2Rate:n(document.getElementById('b_rate2')?.value)/100,loan2Points:n(document.getElementById('b_points')?.value)};}
function renderBuydown(){const host=document.getElementById('buydownResults');if(!host)return;const m=buyState.loan1Years*12,p1=pmt(buyState.loan1Rate/12,m,buyState.loan1Amount),p2=pmt(buyState.loan2Rate/12,m,buyState.loan1Amount),cost=buyState.loan1Amount*.01*buyState.loan2Points,save=p1-p2,be=save?cost/save:NaN;host.innerHTML=`<div class="box"><span>Monthly Savings</span><b>${fmtC(save,2)}</b></div><div class="box"><span>Point Cost</span><b>${fmtC(cost)}</b></div><div class="box"><span>Break-Even</span><b>${Number.isFinite(be)?be.toFixed(1)+' months':'N/A'}</b></div>`;}

function getScenarioState(k){return k==='A'?{mortgage:state.mortgage,mortRate:state.mortRate,loanYears:state.loanYears,interestOnly:state.interestOnly,points:state.points,origFee:state.origFee}:{...scenarioState[k]};}
function readScenarioInputs(){['B','C'].forEach(k=>{['mortgage','mortRate','loanYears','points','origFee'].forEach(f=>{const e=document.getElementById(`sc_${k}_${f}`);if(e)scenarioState[k][f]=n(e.value)/(f==='mortRate'?100:1);});const io=document.getElementById(`sc_${k}_interestOnly`);if(io)scenarioState[k].interestOnly=io.value==='true';});}
function scenarioCardsHtml(){return ['A','B','C'].map(k=>{const s=getScenarioState(k);return `<div class="scenario-card"><h3>Scenario ${k}</h3><div class="field"><label>Mortgage</label><input id="sc_${k}_mortgage" type="number" value="${s.mortgage}" ${k==='A'?'disabled':''}></div><div class="field"><label>Rate %</label><input id="sc_${k}_mortRate" type="number" value="${Number(s.mortRate||0)*100}" ${k==='A'?'disabled':''}></div><div class="field"><label>Years</label><input id="sc_${k}_loanYears" type="number" value="${s.loanYears}" ${k==='A'?'disabled':''}></div><div class="field"><label>Interest Only</label><select id="sc_${k}_interestOnly" ${k==='A'?'disabled':''}><option value="false">NO</option><option value="true" ${s.interestOnly?'selected':''}>YES</option></select></div></div>`;}).join('');}
function renderScenarios(){const host=document.getElementById('scenarioCards');if(host)host.innerHTML=scenarioCardsHtml();const rows=window.PropertyThesisSecondaryEngine?.getScenarios?.();const table=document.getElementById('scenarioTable');if(rows&&table)table.innerHTML=tableHTML(['Scenario','Mortgage','Monthly Payment','DSCR','IRR','NPV'],rows.map(r=>({cells:[cell('Scenario '+r.key),cell(fmtC(Number(r.mortgage)||0)),cell(fmtC(Number(r.monthlyPayment)||0,2)),cell(fmtX(Number(r.dcr))),cell(fmtP(Number(r.IRR))),cell(fmtC(Number(r.NPV)))]})));else{if(table)table.innerHTML='<tbody><tr><td>Protected scenario results are loading…</td></tr></tbody>';window.PropertyThesisSecondaryEngine?.request?.();}}

function renderSupport(){if(!result?.years?.length)return;const y=result.years[0],cap=n(document.getElementById('supportCap')?.value,6.5)/100,dscr=n(document.getElementById('supportDscr')?.value,1.25),margin=(1-state.vacancy)*(1-state.opEx),noiNeed=state.price*cap,rentCap=margin?noiNeed/(12*state.units*margin):NaN,rentDscr=y.debt&&margin?y.debt*dscr/(12*state.units*margin):0;const boxes=document.getElementById('supportBoxes'),nar=document.getElementById('supportNarrative');if(boxes)boxes.innerHTML=`<div class="support-box"><span>NOI Needed</span><b>${fmtC(noiNeed)}</b></div><div class="support-box"><span>Rent for Target Cap</span><b>${fmtC(rentCap,0)}</b></div><div class="support-box"><span>Rent for Target DSCR</span><b>${y.debt?fmtC(rentDscr,0):'No Debt'}</b></div><div class="support-box"><span>Current Rent</span><b>${fmtC(state.rent,0)}</b></div>`;if(nar)nar.innerHTML=`<strong>Support position</strong><p>Current rent is ${state.rent>=rentCap?'above':'below'} the target-cap requirement by ${fmtC(Math.abs(state.rent-rentCap),0)} per month.</p>`;const sens=window.PropertyThesisSecondaryEngine?.getSensitivity?.(),table=document.getElementById('sensitivityTable');if(sens?.cells&&table){const factors=[.95,1,1.05];table.innerHTML=tableHTML(['Price / Rent','-5%','Base','+5%'],factors.map(pf=>({cells:[cell(((pf-1)*100).toFixed(0)+'%'),...factors.map(rf=>{const x=sens.cells.find(v=>Math.abs(Number(v.priceFactor)-pf)<1e-9&&Math.abs(Number(v.rentFactor)-rf)<1e-9);return cell(x?fmtP(Number(x.irr)):'…');})]})));}else{if(table)table.innerHTML='<tbody><tr><td>Protected sensitivity results are loading…</td></tr></tbody>';window.PropertyThesisSecondaryEngine?.request?.();}}
function reportNarrative(){if(!result?.years?.length)return '';const y=result.years[0];return `Year 1 NOI is ${fmtC(y.noi)}, producing a ${fmtP(result.cap)} capitalization rate and ${fmtX(result.grm)} gross rent multiplier. The ${state.hold}-year analysis produces an IRR of ${fmtP(result.IRR)} and NPV of ${fmtC(result.NPV)} at a ${fmtP(state.requiredReturn)} required return.`;}
function renderClientReport(){if(!result?.years?.length)return;const y=result.years[0],host=document.getElementById('clientReport');if(!host)return;host.innerHTML=`<div class="report-cover"><h1>${state.name||'Investment Property Analysis'}</h1><p>${state.address||'Property investment analysis'} • Prepared by Jamie Meloni, Meloni Realty</p></div><div class="report-section"><h2>Executive Conclusion</h2><div class="report-summary">${reportNarrative()}</div></div><div class="report-section"><h2>Investment Snapshot</h2><div class="report-grid"><div class="report-metric"><span>Acquisition Price</span><b>${fmtC(state.price)}</b></div><div class="report-metric"><span>Monthly Rent</span><b>${fmtC(state.rent)}</b></div><div class="report-metric"><span>Year 1 NOI</span><b>${fmtC(y.noi)}</b></div><div class="report-metric"><span>Cap Rate</span><b>${fmtP(result.cap)}</b></div><div class="report-metric"><span>IRR</span><b>${fmtP(result.IRR)}</b></div><div class="report-metric"><span>NPV</span><b>${fmtC(result.NPV)}</b></div></div></div>`;}

function refreshLibrary(){const s=document.getElementById('analysisLibrary');if(!s)return;const lib=JSON.parse(localStorage.getItem('meloniNamedAnalyses')||'{}');s.innerHTML='<option value="">Saved analyses…</option>'+Object.keys(lib).map(k=>`<option>${k}</option>`).join('');}
function saveNamedAnalysis(){readFields();const lib=JSON.parse(localStorage.getItem('meloniNamedAnalyses')||'{}'),k=state.name||'Untitled Analysis';lib[k]={state,buyState,scenarioState};localStorage.setItem('meloniNamedAnalyses',JSON.stringify(lib));refreshLibrary();setStatus('Named analysis saved');}
function loadNamedAnalysis(){const k=document.getElementById('analysisLibrary')?.value,lib=JSON.parse(localStorage.getItem('meloniNamedAnalyses')||'{}');if(!lib[k])return;state={...defaults,...lib[k].state};buyState={...buydownDefaults,...lib[k].buyState};scenarioState={...scenarioState,...lib[k].scenarioState};renderFields();render();setStatus('Named analysis loaded');}
function deleteNamedAnalysis(){const k=document.getElementById('analysisLibrary')?.value,lib=JSON.parse(localStorage.getItem('meloniNamedAnalyses')||'{}');delete lib[k];localStorage.setItem('meloniNamedAnalyses',JSON.stringify(lib));refreshLibrary();setStatus('Named analysis deleted');}
function downloadCSV(){if(!result?.amort)return;const rows=['Year,Month,Payment,Interest,Principal,Balance',...result.amort.map(a=>[a.year,a.month,a.payment,a.interest,a.principal,a.balance].join(','))];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.join('\n')],{type:'text/csv'}));a.download='amortization_schedule.csv';a.click();}
function setStatus(t){const el=document.getElementById('saveStatus');if(!el)return;el.textContent=t;setTimeout(()=>{const cur=document.getElementById('saveStatus');if(cur)cur.textContent='Ready';},1800);}
function switchTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));document.querySelectorAll('.section').forEach(x=>x.classList.toggle('active',x.id===id));}

document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
const on=(id,fn)=>{const el=document.getElementById(id);if(el)el.onclick=fn;};
on('calculateBtn',()=>{readFields();render();switchTab('dashboard');});on('resetBtn',()=>{state={...defaults};renderFields();render();});on('saveBtn',()=>{readFields();localStorage.setItem('meloniInvestmentAnalyzer',JSON.stringify({state,buyState}));setStatus('Saved in browser');});on('loadBtn',()=>{const x=JSON.parse(localStorage.getItem('meloniInvestmentAnalyzer')||'null');if(x){state={...defaults,...x.state};buyState={...buydownDefaults,...x.buyState};renderFields();render();}});on('csvBtn',downloadCSV);on('quickCalc',()=>{state.name=document.getElementById('propertyName')?.value||'';state.price=n(document.getElementById('quickPrice')?.value,state.price);state.rent=n(document.getElementById('quickRent')?.value,state.rent);renderFields();render();});on('buydownCalc',()=>{readBuydown();renderBuydown();});on('saveNamedBtn',saveNamedAnalysis);on('loadNamedBtn',loadNamedAnalysis);on('deleteNamedBtn',deleteNamedAnalysis);on('scenarioCalc',()=>{readScenarioInputs();window.PropertyThesisSecondaryEngine?.clearCache?.();window.PropertyThesisSecondaryEngine?.request?.();renderScenarios();});on('scenarioFromBase',()=>{scenarioState.B={...getScenarioState('A')};scenarioState.C={...getScenarioState('A'),mortgage:0,mortRate:0};window.PropertyThesisSecondaryEngine?.clearCache?.();window.PropertyThesisSecondaryEngine?.request?.();renderScenarios();});on('supportCalc',renderSupport);on('printReportBtn',()=>window.print());on('refreshReportBtn',renderClientReport);on('set80Ltv',()=>{const e=document.getElementById('f_mortgage');if(e)e.value=n(document.getElementById('f_price')?.value)*.8;});on('setCash',()=>{const e=document.getElementById('f_mortgage');if(e)e.value=0;});

// Startup deliberately renders fields only. Financial results are rendered after the authenticated server engine returns.
renderFields();refreshLibrary();