'use strict';
(() => {
  const VERSION=3, BUCKET='report-brand-assets';
  if((window.__profileSystemVersion||0)>=VERSION)return;
  window.__profileSystemVersion=VERSION;

  const DEFAULTS={full_name:'',professional_title:'',company_name:'',email:'',phone:'',website:'',license_number:'',logo_url:'',brand_color:'#174f83',report_footer:'',report_disclaimer:''};
  const OWNER_DEFAULTS={full_name:'Jamie Meloni',professional_title:'Real Estate Broker',company_name:'Meloni Realty',website:'PropertyThesis.com',license_number:'BK3167461 • CQ1067291'};
  const defaultsFor=user=>String(user?.email||'').toLowerCase()==='jrmeloni@hotmail.com'?{...DEFAULTS,...OWNER_DEFAULTS}:DEFAULTS;
  let profile={...DEFAULTS};
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
  const safeColor=v=>/^#[0-9a-f]{6}$/i.test(v||'')?v:'#174f83';
  function client(){try{return typeof cloudClient!=='undefined'?cloudClient:null}catch(e){return null}}
  function neutralize(){document.title='Investment Property Analyzer';const h=document.querySelector('.top .brand h1'),p=document.querySelector('.top .brand p');if(h)h.textContent='Investment Property Analyzer';if(p)p.textContent='Cash flow, valuation, financing, taxes and investment returns';document.querySelectorAll('.print-only .mini').forEach(el=>{el.textContent='Prepared with the Investment Property Analyzer';});}

  function styles(){if($('profileSystemStyles'))return;const s=document.createElement('style');s.id='profileSystemStyles';s.textContent=`
    #profileBrandBtn{padding:6px 9px}.ps-modal{position:fixed;inset:0;z-index:30000;background:rgba(15,23,42,.68);display:grid;place-items:center;padding:20px}.ps-dialog{width:min(1140px,97vw);max-height:94vh;overflow:auto;background:#fff;border-radius:18px;box-shadow:0 30px 90px rgba(0,0,0,.32)}.ps-head{padding:18px 22px;border-bottom:1px solid #e6ebf0;display:flex;justify-content:space-between;gap:16px;align-items:flex-start;background:#f8fafc}.ps-head h2{margin:0;font-size:19px}.ps-head p{margin:4px 0 0;font-size:10px;color:#667085}.ps-layout{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(330px,.9fr)}.ps-edit{padding:22px}.ps-preview{padding:22px;background:#f2f5f8;border-left:1px solid #dfe5eb}.ps-section{margin-bottom:20px}.ps-section h3{margin:0 0 4px;font-size:13px;color:#172033}.ps-section>p{margin:0 0 11px;font-size:9.5px;color:#667085}.ps-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.ps-wide{grid-column:1/-1}.ps-section label{display:block;font-size:9px;font-weight:800;color:#475467;margin-bottom:5px}.ps-section input,.ps-section textarea{width:100%;box-sizing:border-box}.ps-section textarea{min-height:76px;resize:vertical}.ps-logo-row{display:grid;grid-template-columns:130px 1fr;gap:14px;align-items:center;margin-bottom:12px}.ps-logo-box{height:88px;border:1px dashed #bdc9d5;border-radius:11px;background:#fafbfd;display:grid;place-items:center;overflow:hidden;color:#8492a6;font-size:9px;padding:8px;text-align:center}.ps-logo-box img{max-width:100%;max-height:70px;object-fit:contain}#psLogoFile{position:absolute;opacity:0;width:1px;height:1px;pointer-events:none}.ps-help{font-size:8.5px;color:#7b8797;margin-top:6px}.ps-color{display:grid;grid-template-columns:64px 1fr;gap:8px}.ps-color input[type=color]{height:40px;padding:3px}.ps-report{border:1px solid #d9e2ea;border-radius:13px;overflow:hidden;background:#fff;box-shadow:0 12px 30px rgba(25,49,78,.1)}.ps-cover{padding:24px 22px 20px;min-height:190px;background:#174f83;color:#fff}.ps-cover img{height:44px;max-width:150px;object-fit:contain;background:#fff;border-radius:6px;padding:4px;margin-bottom:14px}.ps-company{font-size:9px;letter-spacing:.14em;font-weight:800;opacity:.88}.ps-title{font-size:25px;line-height:1.08;font-weight:850;margin:10px 0 7px}.ps-small{font-size:9px;opacity:.88;line-height:1.5}.ps-body{padding:15px 17px;font-size:9px;color:#667085;line-height:1.55}.ps-actions{position:sticky;bottom:0;padding:15px 22px;border-top:1px solid #e6ebf0;background:#fafbfc;display:flex;justify-content:flex-end;gap:8px;align-items:center}.ps-status{margin-right:auto;font-size:9px;color:#667085}#clientReport .rb-brand-logo{max-width:150px;max-height:54px;object-fit:contain;background:#fff;border-radius:7px;padding:5px;margin-bottom:9px;display:block}
    @media(max-width:900px){.ps-layout{grid-template-columns:1fr}.ps-preview{border-left:0;border-top:1px solid #dfe5eb}}@media(max-width:620px){.ps-grid,.ps-logo-row{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}

  function ensureButton(){const host=document.querySelector('.top .topactions');if(!host)return null;let b=$('profileBrandBtn');if(!b){b=document.createElement('button');b.id='profileBrandBtn';b.type='button';b.className='btn ghost hidden';b.textContent='Profile & Branding';const auth=document.querySelector('.authbar');if(auth)host.insertBefore(b,auth);else host.appendChild(b);}b.onclick=openStudio;return b;}

  async function session(){const c=client();if(!c)return null;try{const {data}=await c.auth.getSession();return data?.session||null}catch(e){return null}}
  async function syncButton(){const b=ensureButton();if(!b)return;const s=await session();b.classList.toggle('hidden',!s?.user);}

  function formData(){return {full_name:$('psFullName').value.trim(),professional_title:$('psTitleField').value.trim(),company_name:$('psCompany').value.trim(),email:$('psEmail').value.trim(),phone:$('psPhone').value.trim(),website:$('psWebsite').value.trim(),license_number:$('psLicense').value.trim(),logo_url:profile.logo_url||'',brand_color:safeColor($('psColorText').value.trim()||$('psColor').value),report_footer:$('psFooter').value.trim(),report_disclaimer:$('psDisclaimer').value.trim()};}
  function refreshPreview(){profile={...profile,...formData()};const c=safeColor(profile.brand_color);$('psCover').style.background=`linear-gradient(125deg,${c},${c} 65%,#334155 140%)`;$('psCompanyPreview').textContent=(profile.company_name||'YOUR COMPANY').toUpperCase();$('psByline').textContent='Prepared by '+([profile.full_name||'Your Name',profile.professional_title].filter(Boolean).join(' • '));$('psContact').textContent=[profile.email,profile.phone,profile.website].filter(Boolean).join(' • ')||'Email • Phone • Website';const img=$('psLogoPreview'),box=$('psLogoBox');if(profile.logo_url){img.src=profile.logo_url;img.style.display='block';box.innerHTML=`<img src="${esc(profile.logo_url)}" alt="Logo">`;}else{img.style.display='none';img.removeAttribute('src');box.innerHTML='<span>No logo uploaded</span>';}}
  function fill(p){profile={...DEFAULTS,...p};$('psCompany').value=profile.company_name||'';$('psColor').value=safeColor(profile.brand_color);$('psColorText').value=safeColor(profile.brand_color);$('psFullName').value=profile.full_name||'';$('psTitleField').value=profile.professional_title||'';$('psLicense').value=profile.license_number||'';$('psEmail').value=profile.email||'';$('psPhone').value=profile.phone||'';$('psWebsite').value=profile.website||'';$('psFooter').value=profile.report_footer||'';$('psDisclaimer').value=profile.report_disclaimer||'';refreshPreview();}
  function status(t){if($('psStatus'))$('psStatus').textContent=t}
  function closeStudio(){$('profileSystemModal')?.remove()}

  function buildStudio(){closeStudio();const m=document.createElement('div');m.id='profileSystemModal';m.className='ps-modal';m.innerHTML=`<div class="ps-dialog"><div class="ps-head"><div><h2>Profile & Report Branding</h2><p>Create the professional identity used on your client-facing reports.</p></div><button class="btn ghost" id="psClose" type="button">Close</button></div><div class="ps-layout"><div class="ps-edit">
  <section class="ps-section"><h3>Brand Identity</h3><p>Upload your logo and choose the primary color used on report covers and accents.</p><div class="ps-logo-row"><div class="ps-logo-box" id="psLogoBox">No logo uploaded</div><div><label class="btn secondary" for="psLogoFile">Upload Logo</label><input id="psLogoFile" type="file" accept="image/png,image/jpeg,image/webp,image/gif"><button class="btn ghost" id="psRemoveLogo" type="button" style="margin-left:6px">Remove Logo</button><div class="ps-help" id="psLogoStatus">PNG, JPG, WEBP or GIF. Maximum 2 MB.</div></div></div><div class="ps-grid"><div><label>Company / Brand Name</label><input id="psCompany"></div><div><label>Primary Brand Color</label><div class="ps-color"><input id="psColor" type="color"><input id="psColorText"></div></div></div></section>
  <section class="ps-section"><h3>Professional Identity</h3><div class="ps-grid"><div><label>Full Name</label><input id="psFullName"></div><div><label>Professional Title</label><input id="psTitleField"></div><div class="ps-wide"><label>License / Credential Number</label><input id="psLicense"></div></div></section>
  <section class="ps-section"><h3>Contact Information</h3><div class="ps-grid"><div><label>Email</label><input id="psEmail" type="email"></div><div><label>Phone</label><input id="psPhone"></div><div class="ps-wide"><label>Website</label><input id="psWebsite"></div></div></section>
  <section class="ps-section"><h3>Report Branding</h3><div class="ps-grid"><div class="ps-wide"><label>Report Footer</label><input id="psFooter"></div><div class="ps-wide"><label>Custom Report Disclaimer</label><textarea id="psDisclaimer"></textarea></div></div></section>
  </div><aside class="ps-preview"><div style="font-size:8px;font-weight:850;letter-spacing:.12em;text-transform:uppercase;color:#667085;margin-bottom:8px">Live report preview</div><div class="ps-report"><div class="ps-cover" id="psCover"><img id="psLogoPreview" alt="Logo" style="display:none"><div class="ps-company" id="psCompanyPreview">YOUR COMPANY</div><div class="ps-title">Investment Property Analysis</div><div class="ps-small">123 Sample Property Address</div><div class="ps-small" id="psByline" style="margin-top:18px">Prepared by Your Name</div></div><div class="ps-body">Executive Investment Conclusion<br><span id="psContact">Email • Phone • Website</span></div></div></aside></div><div class="ps-actions"><span class="ps-status" id="psStatus"></span><button class="btn secondary" id="psCancel" type="button">Cancel</button><button class="btn primary" id="psSave" type="button">Save Profile</button></div></div>`;document.body.appendChild(m);
  $('psClose').onclick=closeStudio;$('psCancel').onclick=closeStudio;$('psSave').onclick=saveProfile;$('psLogoFile').onchange=uploadLogo;$('psRemoveLogo').onclick=()=>{profile.logo_url='';refreshPreview();};['psCompany','psColor','psColorText','psFullName','psTitleField','psLicense','psEmail','psPhone','psWebsite','psFooter','psDisclaimer'].forEach(id=>$(id).addEventListener('input',()=>{if(id==='psColor')$('psColorText').value=$('psColor').value;if(id==='psColorText'&&/^#[0-9a-f]{6}$/i.test($('psColorText').value))$('psColor').value=$('psColorText').value;refreshPreview();}));}

  async function loadProfile(){const s=await session();const c=client();if(!s?.user||!c){profile={...DEFAULTS};return profile;}const base=defaultsFor(s.user);const {data,error}=await c.from('profiles').select('*').eq('user_id',s.user.id).maybeSingle();if(error){console.error('Profile load failed',error);profile={...base,email:s.user.email||''};return profile;}profile={...base,...(data||{}),email:data?.email||s.user.email||''};applyReportBranding();return profile;}
  async function openStudio(){const s=await session();if(!s?.user){try{showAuth()}catch(e){}return;}buildStudio();fill({...profile,email:profile.email||s.user.email||''});status('Loading profile…');await loadProfile();fill(profile);status('');}
  async function saveProfile(){const s=await session(),c=client();if(!s?.user||!c)return status('Sign in to save your profile.');const fields=Object.fromEntries(Object.entries(formData()).map(([key,value])=>[key,value===''?null:value]));profile={...profile,...fields};status('Saving profile…');const {data,error}=await c.from('profiles').upsert({user_id:s.user.id,...fields,updated_at:new Date().toISOString()},{onConflict:'user_id'}).select().single();if(error)return status(error.message);profile={...DEFAULTS,...data};status('Profile saved.');applyReportBranding();setTimeout(closeStudio,350);}
  async function uploadLogo(e){const file=e.target.files?.[0],s=await session(),c=client();if(!file||!s?.user||!c)return;if(!/^image\/(png|jpeg|webp|gif)$/i.test(file.type))return $('psLogoStatus').textContent='Choose a PNG, JPG, WEBP or GIF.';if(file.size>2*1024*1024)return $('psLogoStatus').textContent='Logo must be 2 MB or smaller.';const ext=(file.name.split('.').pop()||'png').replace(/[^a-z0-9]/gi,'').toLowerCase();const path=`${s.user.id}/logo-${Date.now()}.${ext}`;$('psLogoStatus').textContent='Uploading logo…';const r=await c.storage.from(BUCKET).upload(path,file,{contentType:file.type,cacheControl:'31536000',upsert:false});if(r.error)return $('psLogoStatus').textContent=r.error.message;profile.logo_url=c.storage.from(BUCKET).getPublicUrl(r.data.path).data?.publicUrl||'';$('psLogoStatus').textContent='Logo uploaded. Save profile to apply.';refreshPreview();e.target.value='';}

  function applyReportBranding(){const report=document.querySelector('#clientReport .rb-report');if(!report)return false;const color=safeColor(profile.brand_color);const cover=report.querySelector('.rb-cover');if(cover)cover.style.background=`linear-gradient(125deg,${color} 0%,${color} 62%,#334155 135%)`;const company=profile.company_name||'PropertyThesis';const brand=report.querySelector('.rb-brand');if(brand)brand.textContent=company.toUpperCase();cover?.querySelector('.rb-brand-logo')?.remove();if(cover&&profile.logo_url){const img=document.createElement('img');img.className='rb-brand-logo';img.src=profile.logo_url;img.alt=company+' logo';brand?.insertAdjacentElement('beforebegin',img);}const meta=cover?.querySelector('.rb-meta');if(meta){const who=[profile.full_name,profile.professional_title,profile.license_number].filter(Boolean).join(' • ')||'PropertyThesis';const contact=[profile.email,profile.phone,profile.website].filter(Boolean).join(' • ');[...meta.querySelectorAll('span')].forEach(s=>{if(/Prepared by:/i.test(s.textContent||''))s.innerHTML=`<b>Prepared by:</b> ${esc(who)}`;});meta.querySelector('.rb-profile-contact')?.remove();if(contact)meta.insertAdjacentHTML('beforeend',`<span class="rb-profile-contact"><b>Contact:</b> ${esc(contact)}</span>`);}const footer=report.querySelector('.rb-footer');if(footer){const brandEl=footer.querySelector('.rb-footer-brand');if(brandEl)brandEl.textContent=company;footer.querySelector('.rb-profile-footer')?.remove();if(profile.report_footer||profile.report_disclaimer){const d=document.createElement('div');d.className='rb-profile-footer';d.textContent=[profile.report_footer,profile.report_disclaimer].filter(Boolean).join(' • ');footer.prepend(d);}}return true;}

  function getProfile(){return {...profile};}
  function start(){styles();neutralize();ensureButton();syncButton();loadProfile();const c=client();try{c?.auth?.onAuthStateChange?.(()=>{setTimeout(syncButton,0);setTimeout(loadProfile,50);});}catch(e){}document.addEventListener('click',e=>{if(e.target?.closest?.('[data-s8-tab="report"],[data-tab="report"],#rbRefresh,#rbSelectCore,#rbSelectAll'))setTimeout(applyReportBranding,120);},true);setInterval(()=>{neutralize();syncButton();applyReportBranding();},1200);}
  window.UserBranding={getProfile,loadProfile,applyReportBranding,openProfile:openStudio};
  window.ProfileSystem={open:openStudio,save:saveProfile};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
