import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const corsHeaders={"Access-Control-Allow-Origin":"https://propertythesis.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
function json(body:unknown,status=200,extraHeaders:Record<string,string>={}){return new Response(JSON.stringify(body),{status,headers:{...corsHeaders,...extraHeaders,"Content-Type":"application/json"}})}
function jwtSub(req:Request):string|null{const auth=req.headers.get("authorization")||"",token=auth.replace(/^Bearer\s+/i,"").trim();if(!token)return null;try{const payload=token.split(".")[1];if(!payload)return null;const normalized=payload.replace(/-/g,"+").replace(/_/g,"/");const padded=normalized+"=".repeat((4-normalized.length%4)%4);const data=JSON.parse(atob(padded));return typeof data?.sub==="string"&&data.sub?data.sub:null}catch{return null}}
async function consumeLimit(userId:string,fn:string,limit:number,windowSeconds:number){const url=Deno.env.get("SUPABASE_URL"),serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!serviceKey)throw new Error("Rate limiter is not configured");const r=await fetch(`${url}/rest/v1/rpc/consume_edge_rate_limit`,{method:"POST",headers:{"Content-Type":"application/json","apikey":serviceKey,"Authorization":`Bearer ${serviceKey}`},body:JSON.stringify({p_user_id:userId,p_function_name:fn,p_limit:limit,p_window_seconds:windowSeconds})});if(!r.ok)throw new Error(`Rate limiter failed (${r.status})`);return await r.json()}
async function enforceLimits(req:Request){const userId=jwtSub(req);if(!userId)return{response:json({error:"Authenticated user identity is required"},401)};const burst=await consumeLimit(userId,"propertythesis-income-engine",120,60);if(!burst?.allowed){const retry=Math.max(1,Math.ceil((new Date(burst.reset_at).getTime()-Date.now())/1000));return{response:json({error:"Rate limit exceeded",scope:"minute",retryAfter:retry},429,{"Retry-After":String(retry)})}}const daily=await consumeLimit(userId,"propertythesis-income-engine",5000,86400);if(!daily?.allowed){const retry=Math.max(1,Math.ceil((new Date(daily.reset_at).getTime()-Date.now())/1000));return{response:json({error:"Daily calculation limit exceeded",scope:"day",retryAfter:retry},429,{"Retry-After":String(retry)})}}return{userId}}
const finite=(v:unknown)=>Number.isFinite(Number(v));
const num=(v:unknown,d=0)=>finite(v)?Number(v):d;
const clamp=(x:number,a:number,b:number)=>Math.min(b,Math.max(a,x));
function pmt(r:number,m:number,p:number){return m?(r?r*p/(1-Math.pow(1+r,-m)):p/m):0}
function npv(r:number,c:number[]){return c.reduce((s,v,i)=>s+v/Math.pow(1+r,i),0)}
function irr(c:number[]){if(!c.some(x=>x<0)||!c.some(x=>x>0))return null;let lo=-.9999,hi=10;const f=(x:number)=>c.reduce((s,v,i)=>s+v/Math.pow(1+x,i),0);let fl=f(lo),fh=f(hi);for(let k=0;k<15&&fl*fh>0;k++){hi*=2;fh=f(hi)}if(fl*fh>0)return null;for(let i=0;i<150;i++){const m=(lo+hi)/2,fm=f(m);if(fl*fm<=0){hi=m;fh=fm}else{lo=m;fl=fm}}return(lo+hi)/2}
function normalizeState(raw:any){const price=Math.max(0,num(raw?.price));const land=clamp(num(raw?.land),0,price);return{name:String(raw?.name||""),address:String(raw?.address||""),price,land,units:Math.max(1,Math.round(num(raw?.units,1))),rent:Math.max(0,num(raw?.rent)),rentGrowth:num(raw?.rentGrowth),vacancy:clamp(num(raw?.vacancy),0,1),opEx:clamp(num(raw?.opEx),0,1),depLife:Math.max(.01,num(raw?.depLife,27.5)),appreciation:num(raw?.appreciation),hold:clamp(Math.round(num(raw?.hold,1)),1,40),sellCost:clamp(num(raw?.sellCost),0,1),mortgage:Math.max(0,num(raw?.mortgage)),interestOnly:!!raw?.interestOnly,mortRate:Math.max(0,num(raw?.mortRate)),loanYears:clamp(Math.round(num(raw?.loanYears,1)),1,40),points:Math.max(0,num(raw?.points)),origFee:Math.max(0,num(raw?.origFee)),ordinaryTax:num(raw?.ordinaryTax),depTax:num(raw?.depTax),capGainsTax:num(raw?.capGainsTax),requiredReturn:num(raw?.requiredReturn),desiredCap:num(raw?.desiredCap),desiredGrm:num(raw?.desiredGrm),initialRepairs:Math.max(0,num(raw?.initialRepairs))}}
function analyze(raw:any){const s=normalizeState(raw),months=s.loanYears*12,mr=s.mortRate/12,mp=s.interestOnly?s.mortgage*mr:pmt(mr,months,s.mortgage);let bal=s.mortgage;const amort:any[]=[];for(let m=1;m<=months;m++){const interest=bal*mr;let principal=s.interestOnly?0:mp-interest,payment=mp;if(!s.interestOnly&&m===months){principal=bal;payment=interest+principal}bal=Math.max(0,bal-principal);amort.push({year:Math.ceil(m/12),month:m,payment,interest,principal,balance:bal})}const pointCost=s.mortgage*.01*s.points,dep=(s.price-s.land)/s.depLife,ap=s.loanYears?pointCost/s.loanYears:0,ao=s.loanYears?s.origFee/s.loanYears:0;const years:any[]=[];let eb=s.mortgage;for(let y=1;y<=s.hold;y++){const pgi=s.rent*Math.pow(1+s.rentGrowth,y-1)*12*s.units,vac=pgi*s.vacancy,egi=pgi-vac,opex=egi*s.opEx,noi=egi-opex,rows=amort.filter(a=>a.year===y),debt=rows.reduce((a,b)=>a+b.payment,0),interest=rows.reduce((a,b)=>a+b.interest,0),principal=debt-interest;eb=Math.max(0,eb-principal);const taxable=noi-interest-dep-(y<=s.loanYears?ap+ao:0),opTax=taxable*s.ordinaryTax,atcf=noi-debt-opTax;years.push({year:y,pgi,vac,egi,opex,noi,debt,interest,principal,endBalance:eb,taxable,opTax,atcf,dcr:debt?noi/debt:null})}if(s.interestOnly&&s.loanYears>0){for(const yr of years)yr.endBalance=yr.year<=s.loanYears?s.mortgage:0}const grossSale=s.price*Math.pow(1+s.appreciation,s.hold),selling=grossSale*s.sellCost,netSale=grossSale-selling,accDep=dep*s.hold,book=s.price-accDep,gain=netSale-book,gainRate=s.hold===1?s.ordinaryTax:s.capGainsTax,saleTax=gain*gainRate+accDep*s.depTax,loanPayoff=years.at(-1)?.endBalance||0,ater=netSale-loanPayoff-saleTax,initial=-(s.price-s.mortgage+pointCost+s.origFee+s.initialRepairs),cfs=[initial,...years.map((y,i)=>y.atcf+(i===years.length-1?ater:0))],totalProjectCost=s.price+s.initialRepairs,y1noi=years[0]?.noi??null;return{amort,years,depreciation:dep,pointCost,grossSale,selling,netSale,accDep,book,gain,saleTax,loanPayoff,ater,initial,cfs,IRR:irr(cfs),NPV:npv(s.requiredReturn,cfs),cap:s.price&&y1noi!=null?y1noi/s.price:null,grm:years[0]?.pgi?s.price/years[0].pgi:null,capValue:s.desiredCap&&y1noi!=null?y1noi/s.desiredCap:null,grmValue:years[0]?.pgi!=null?years[0].pgi*s.desiredGrm:null,monthlyPayment:mp,initialRepairs:s.initialRepairs,totalProjectCost,yieldOnCost:totalProjectCost>0&&y1noi!=null?y1noi/totalProjectCost:null,engineVersion:3}}
function scenarioAtPrice(base:any,price:number){const b=normalizeState(base),ltv=b.price?Math.max(0,b.mortgage/b.price):0,landRatio=b.price?Math.max(0,b.land/b.price):0;return{...base,price,mortgage:b.mortgage>0?price*ltv:0,land:clamp(price*landRatio,0,price)}}
function metricForPrice(base:any,price:number,key:string){const r=analyze(scenarioAtPrice(base,price));return Number(key==='irr'?r.IRR:r.cap)}
function metricForRent(base:any,rent:number,key:string){const r=analyze({...base,rent});return Number(key==='irr'?r.IRR:r.cap)}
function maxPriceFor(base:any,key:string,target:number){const current=num(base?.price);if(!current||!finite(target)||target<=0)return null;let lo=Math.max(1000,current*.10),hi=Math.max(current*3,lo*2),flo=metricForPrice(base,lo,key),fhi=metricForPrice(base,hi,key),guard=0;while((!finite(flo)||flo<target)&&lo>1000&&guard++<6){lo=Math.max(1000,lo*.5);flo=metricForPrice(base,lo,key)}guard=0;while(finite(fhi)&&fhi>=target&&guard++<6){hi*=1.8;fhi=metricForPrice(base,hi,key)}if(!finite(flo)||flo<target)return null;if(!finite(fhi)){let test=hi;for(let i=0;i<8&&!finite(fhi);i++){test=(lo+test)/2;fhi=metricForPrice(base,test,key);hi=test}if(!finite(fhi))return null}if(fhi>=target)return hi;for(let i=0;i<42;i++){const mid=(lo+hi)/2,f=metricForPrice(base,mid,key);if(!finite(f)){hi=mid;continue}if(f>=target)lo=mid;else hi=mid}return lo}
function minRentFor(base:any,key:string,target:number){const current=Math.max(100,num(base?.rent));if(!finite(target)||target<=0)return null;let lo=Math.max(50,current*.20),hi=Math.max(500,current*2),flo=metricForRent(base,lo,key),fhi=metricForRent(base,hi,key),guard=0;while((!finite(fhi)||fhi<target)&&guard++<8){hi*=1.6;fhi=metricForRent(base,hi,key)}if(!finite(fhi)||fhi<target)return null;if(finite(flo)&&flo>=target)return lo;for(let i=0;i<42;i++){const mid=(lo+hi)/2,f=metricForRent(base,mid,key);if(!finite(f)){lo=mid;continue}if(f>=target)hi=mid;else lo=mid}return hi}
function offerAnalysis(state:any){const base=normalizeState(state),r=analyze(state),y1=r.years[0],desiredCap=base.desiredCap,requiredReturn=base.requiredReturn,price=base.price,rent=base.rent,openingDiscount=finite(state?.offerAnalysis?.openingDiscount)?clamp(Number(state.offerAnalysis.openingDiscount),0,.25):.05;const capPrice=desiredCap>0&&finite(y1?.noi)?Number(y1.noi)/desiredCap:null,irrPrice=maxPriceFor(state,'irr',requiredReturn),supported=[capPrice,irrPrice].filter(finite).map(Number),maxSupported=supported.length?Math.min(...supported):null,opening=finite(maxSupported)?Number(maxSupported)*(1-openingDiscount):null,capRent=minRentFor(state,'cap',desiredCap),irrRent=minRentFor(state,'irr',requiredReturn),gap=finite(maxSupported)?price-Number(maxSupported):null,gapPct=finite(gap)&&finite(maxSupported)&&Number(maxSupported)!==0?Number(gap)/Number(maxSupported):null,ladder=[.05,.06,.07,.08].map(rate=>({rate,price:finite(y1?.noi)?Number(y1.noi)/rate:null}));return{y1,desiredCap,requiredReturn,price,rent,capPrice,irrPrice,maxSupported,opening,openingDiscount,capRent,irrRent,gap,gapPct,ladder,cap:r.cap,IRR:r.IRR}}
function sensitivity(state:any){const priceFactors=[.90,.95,1,1.05,1.10],rentFactors=[.90,.95,1,1.05,1.10],b=normalizeState(state),ltv=b.price?b.mortgage/b.price:0,landRatio=b.price?b.land/b.price:0,cells:any[]=[];for(const pf of priceFactors){for(const rf of rentFactors){const price=b.price*pf,ss={...state,price,rent:b.rent*rf,land:clamp(price*landRatio,0,price),mortgage:b.mortgage>0?price*ltv:0},r=analyze(ss);cells.push({priceFactor:pf,rentFactor:rf,irr:r.IRR,npv:r.NPV,cap:r.cap,atcf:r.years[0]?.atcf??null})}}return{priceFactors,rentFactors,cells}}
function scenarios(state:any,scenarioState:any){const a={mortgage:num(state?.mortgage),mortRate:num(state?.mortRate),loanYears:num(state?.loanYears),interestOnly:!!state?.interestOnly,points:num(state?.points),origFee:num(state?.origFee)},b={...a,...(scenarioState?.B||{})},c={...a,...(scenarioState?.C||{})};return['A','B','C'].map((key,i)=>{const terms=[a,b,c][i],r=analyze({...state,...terms});return{key,mortgage:terms.mortgage,monthlyPayment:r.monthlyPayment,dcr:r.years[0]?.dcr??null,IRR:r.IRR,NPV:r.NPV}})}
function secondary(state:any,scenarioState:any){return{offer:offerAnalysis(state),sensitivity:sensitivity(state),scenarios:scenarios(state,scenarioState),engineVersion:3}}
function analyzeBatch(items:any[]){return items.slice(0,50).map(s=>analyze(s))}
Deno.serve(async req=>{const origin=req.headers.get('origin');if(origin&&origin!=='https://propertythesis.com')return json({error:'Origin not allowed'},403);if(req.method==='OPTIONS')return new Response('ok',{headers:corsHeaders});if(req.method!=='POST')return json({error:'Method not allowed'},405);try{const limited=await enforceLimits(req);if(limited.response)return limited.response}catch(e){return json({error:'Request protection unavailable'},503)}let body:any;try{body=await req.json()}catch{return json({error:'Invalid JSON body'},400)}try{const action=String(body?.action||'analyze');if(action==='analyze')return json({result:analyze(body?.state||body)});if(action==='batch'){if(!Array.isArray(body?.states))return json({error:'states array is required'},400);return json({results:analyzeBatch(body.states)})}if(action==='secondary')return json({result:secondary(body?.state||{},body?.scenarioState||{})});return json({error:'Unknown action'},400)}catch(e){return json({error:'Calculation failed'},400)}});
