import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const corsHeaders={"Access-Control-Allow-Origin":"https://propertythesis.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200,extra:Record<string,string>={})=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,...extra,"Content-Type":"application/json"}});

function jwtSub(req:Request){const auth=req.headers.get("authorization")||"";const token=auth.replace(/^Bearer\s+/i,"").trim();if(!token)return null;try{const p=token.split(".")[1];if(!p)return null;const n=p.replace(/-/g,"+").replace(/_/g,"/");const d=JSON.parse(atob(n+"=".repeat((4-n.length%4)%4)));return typeof d?.sub==="string"&&d.sub?d.sub:null;}catch{return null;}}
async function consume(userId:string,limit:number,windowSeconds:number){const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw new Error("Rate limiter is not configured");const r=await fetch(`${url}/rest/v1/rpc/consume_edge_rate_limit`,{method:"POST",headers:{"Content-Type":"application/json","apikey":key,"Authorization":`Bearer ${key}`},body:JSON.stringify({p_user_id:userId,p_function_name:"rentcast-property-lookup",p_limit:limit,p_window_seconds:windowSeconds})});if(!r.ok)throw new Error(`Rate limiter failed (${r.status})`);return await r.json();}
async function protect(req:Request){const id=jwtSub(req);if(!id)return json({error:"Authenticated user identity is required"},401);for(const [limit,seconds,scope] of [[20,60,"minute"],[200,86400,"day"]] as const){const x=await consume(id,limit,seconds);if(!x?.allowed){const retry=Math.max(1,Math.ceil((new Date(x.reset_at).getTime()-Date.now())/1000));return json({error:"Rate limit exceeded",scope,retryAfter:retry},429,{"Retry-After":String(retry)});}}return null;}

function normalized(p:any){if(!p)return null;return {id:p.id??null,formattedAddress:p.formattedAddress??null,addressLine1:p.addressLine1??null,addressLine2:p.addressLine2??null,city:p.city??null,state:p.state??null,zipCode:p.zipCode??null,county:p.county??null,latitude:p.latitude??null,longitude:p.longitude??null,propertyType:p.propertyType??null,bedrooms:p.bedrooms??null,bathrooms:p.bathrooms??null,squareFootage:p.squareFootage??null,lotSize:p.lotSize??null,yearBuilt:p.yearBuilt??null,assessorID:p.assessorID??null,legalDescription:p.legalDescription??null,subdivision:p.subdivision??null,zoning:p.zoning??null,lastSaleDate:p.lastSaleDate??null,lastSalePrice:p.lastSalePrice??null,features:p.features??null,taxAssessments:p.taxAssessments??null,propertyTaxes:p.propertyTaxes??null,source:"RentCast"};}

Deno.serve(async(req)=>{const origin=req.headers.get("origin");if(origin&&origin!=="https://propertythesis.com")return json({error:"Origin not allowed"},403);if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{const blocked=await protect(req);if(blocked)return blocked;}catch(e){return json({error:"Request protection unavailable"},503);}const apiKey=Deno.env.get("RENTCAST_API_KEY");if(!apiKey)return json({error:"Listing data service is not configured"},503);let body:any;try{body=await req.json();}catch{return json({error:"Invalid JSON body"},400);}const address=String(body?.address||"").trim();if(!address)return json({error:"Property address is required"},400);const params=new URLSearchParams({address,limit:"5"});try{const r=await fetch(`https://api.rentcast.io/v1/properties?${params.toString()}`,{headers:{"Accept":"application/json","X-Api-Key":apiKey}});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null;}catch{data={raw:text};}if(!r.ok)return json({error:"RentCast request failed",status:r.status},r.status);const records=Array.isArray(data)?data:[];if(!records.length)return json({matched:false,address,property:null,candidates:[],source:"RentCast"});return json({matched:true,address,property:normalized(records[0]),candidates:records.slice(0,5).map(normalized),source:"RentCast"});}catch(e){return json({error:"Unable to reach RentCast"},502);}});
