create table if not exists public.external_api_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null,
  endpoint text not null,
  created_at timestamptz not null default now()
);

create index if not exists external_api_usage_provider_created_idx
  on public.external_api_usage (provider, created_at desc);
create index if not exists external_api_usage_user_created_idx
  on public.external_api_usage (user_id, created_at desc);

alter table public.external_api_usage enable row level security;
revoke all on table public.external_api_usage from anon, authenticated;

create table if not exists public.external_api_cache (
  cache_key text primary key,
  provider text not null,
  endpoint text not null,
  payload jsonb not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index if not exists external_api_cache_expires_idx
  on public.external_api_cache (expires_at);

alter table public.external_api_cache enable row level security;
revoke all on table public.external_api_cache from anon, authenticated;


