create table if not exists public.guest_external_api_usage (
  id bigint generated by default as identity primary key,
  guest_key_hash text not null,
  provider text not null,
  endpoint text not null,
  created_at timestamptz not null default now()
);

create index if not exists guest_external_api_usage_key_created_idx
  on public.guest_external_api_usage (guest_key_hash, created_at desc);
create index if not exists guest_external_api_usage_provider_created_idx
  on public.guest_external_api_usage (provider, created_at desc);

alter table public.guest_external_api_usage enable row level security;
revoke all on table public.guest_external_api_usage from anon, authenticated;
