import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const corsHeaders={"Access-Control-Allow-Origin":"https://propertythesis.com","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200,extra:Record<string,string>={})=>new Response(JSON.stringify(body),{status,headers:{...corsHeaders,...extra,"Content-Type":"application/json"}});
function jwtSub(req:Request){const auth=req.headers.get("authorization")||"";const token=auth.replace(/^Bearer\s+/i,"").trim();if(!token)return null;try{const p=token.split(".")[1];if(!p)return null;const n=p.replace(/-/g,"+").replace(/_/g,"/");const d=JSON.parse(atob(n+"=".repeat((4-n.length%4)%4)));return typeof d?.sub==="string"&&d.sub?d.sub:null;}catch{return null;}}
async function consume(userId:string,limit:number,windowSeconds:number){const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");if(!url||!key)throw new Error("Rate limiter is not configured");const r=await fetch(`${url}/rest/v1/rpc/consume_edge_rate_limit`,{method:"POST",headers:{"Content-Type":"application/json","apikey":key,"Authorization":`Bearer ${key}`},body:JSON.stringify({p_user_id:userId,p_function_name:"rentcast-sales-comps",p_limit:limit,p_window_seconds:windowSeconds})});if(!r.ok)throw new Error(`Rate limiter failed (${r.status})`);return await r.json();}
async function protect(req:Request){const id=jwtSub(req);if(!id)return json({error:"Authenticated user identity is required"},401);for(const [limit,seconds,scope] of [[12,60,"minute"],[120,86400,"day"]] as const){const x=await consume(id,limit,seconds);if(!x?.allowed){const retry=Math.max(1,Math.ceil((new Date(x.reset_at).getTime()-Date.now())/1000));return json({error:"Rate limit exceeded",scope,retryAfter:retry},429,{"Retry-After":String(retry)});}}return null;}
const num=(v:any)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const clean=(v:any)=>String(v??"").trim();
function range(v:any,minFloor:number|null=null,maxCeil:number|null=null){if(v==null||v==="")return null;if(Array.isArray(v)&&v.length>=2){let a=num(v[0]),b=num(v[1]);if(a==null||b==null)return null;if(a>b)[a,b]=[b,a];if(minFloor!=null)a=Math.max(minFloor,a);if(maxCeil!=null)b=Math.min(maxCeil,b);return `${a}:${b}`;}const s=clean(v);if(!s)return null;if(/^\d+(?:\.\d+)?:\d+(?:\.\d+)?$/.test(s))return s;const n=num(s);return n==null?null:String(n);}
function boolish(v:any):boolean|null{if(v===true||v===1||String(v).toLowerCase()==="true"||String(v).toLowerCase()==="yes")return true;if(v===false||v===0||String(v).toLowerCase()==="false"||String(v).toLowerCase()==="no")return false;return null;}
function poolInfo(p:any){const f=p?.features||{};let has=boolish(f.pool);const type=clean(f.poolType)||null;if(has==null&&type)has=true;return {hasPool:has,poolType:type};}
function miles(aLat:number,aLon:number,bLat:number,bLon:number){const R=3958.7613,toRad=(x:number)=>x*Math.PI/180;const dLat=toRad(bLat-aLat),dLon=toRad(bLon-aLon);const s=Math.sin(dLat/2)**2+Math.cos(toRad(aLat))*Math.cos(toRad(bLat))*Math.sin(dLon/2)**2;return 2*R*Math.asin(Math.min(1,Math.sqrt(s)));}
function closeness(diff:number,scale:number){return Math.max(0,1-Math.min(1,Math.abs(diff)/scale));}
function score(subject:any,c:any,dist:number|null,days:number|null){let total=0,weight=0;const add=(s:number|null,w:number)=>{if(s==null||!Number.isFinite(s))return;total+=Math.max(0,Math.min(1,s))*w;weight+=w;};add(subject.propertyType&&c.propertyType?String(subject.propertyType)===String(c.propertyType)?1:.15:null,22);add(dist!=null?closeness(dist,3):null,19);const sf=num(subject.squareFootage),csf=num(c.squareFootage);add(sf&&csf?closeness((csf-sf)/sf,0.45):null,17);const y=num(subject.yearBuilt),cy=num(c.yearBuilt);add(y&&cy?closeness(cy-y,35):null,9);const b=num(subject.bedrooms),cb=num(c.bedrooms);add(b!=null&&cb!=null?closeness(cb-b,2):null,7);const ba=num(subject.bathrooms),cba=num(c.bathrooms);add(ba!=null&&cba!=null?closeness(cba-ba,2):null,6);const lot=num(subject.lotSize),clot=num(c.lotSize);add(lot&&clot?closeness((clot-lot)/lot,1.25):null,5);add(days!=null?closeness(days,540):null,7);const sp=poolInfo(subject).hasPool,cp=poolInfo(c).hasPool;add(sp!=null&&cp!=null?(sp===cp?1:0):null,8);return weight?Math.round(total/weight*100):0;}
function normalized(subject:any,p:any){const lat=num(p.latitude),lon=num(p.longitude),slat=num(subject.latitude),slon=num(subject.longitude);const dist=lat!=null&&lon!=null&&slat!=null&&slon!=null?miles(slat,slon,lat,lon):null;const saleDate=p.lastSaleDate||null;const days=saleDate?Math.max(0,Math.round((Date.now()-new Date(saleDate).getTime())/86400000)):null;const price=num(p.lastSalePrice),sf=num(p.squareFootage),pool=poolInfo(p);return {id:p.id??null,formattedAddress:p.formattedAddress??null,addressLine1:p.addressLine1??null,city:p.city??null,state:p.state??null,zipCode:p.zipCode??null,latitude:lat,longitude:lon,propertyType:p.propertyType??null,bedrooms:num(p.bedrooms),bathrooms:num(p.bathrooms),squareFootage:sf,lotSize:num(p.lotSize),yearBuilt:num(p.yearBuilt),subdivision:p.subdivision??null,hasPool:pool.hasPool,poolType:pool.poolType,lastSaleDate:saleDate,lastSalePrice:price,pricePerSquareFoot:price&&sf?Math.round(price/sf*100)/100:null,distanceMiles:dist!=null?Math.round(dist*100)/100:null,daysSinceSale:days,similarityScore:score(subject,p,dist,days),source:"RentCast Public Records"};}
Deno.serve(async(req)=>{const origin=req.headers.get("origin");if(origin&&origin!=="https://propertythesis.com")return json({error:"Origin not allowed"},403);if(req.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(req.method!=="POST")return json({error:"Method not allowed"},405);try{const blocked=await protect(req);if(blocked)return blocked;}catch(e){return json({error:"Request protection unavailable"},503);}const apiKey=Deno.env.get("RENTCAST_API_KEY");if(!apiKey)return json({error:"Listing data service is not configured"},503);let body:any;try{body=await req.json();}catch{return json({error:"Invalid JSON body"},400);}const subject=body?.subject||{};const address=clean(subject.formattedAddress||body?.address);if(!address)return json({error:"Subject address is required"},400);const radius=Math.min(10,Math.max(.25,Number(body?.radius)||3));const saleDateRange=Math.min(1095,Math.max(30,Math.round(Number(body?.saleDateRange)||365)));const limit=Math.min(100,Math.max(10,Math.round(Number(body?.limit)||60)));const f=body?.filters||{};const params=new URLSearchParams({address,radius:String(radius),saleDateRange:String(saleDateRange),limit:String(limit)});
const propertyType=clean(f.propertyType);if(propertyType)params.set("propertyType",propertyType);
const bedrooms=range(f.bedrooms,0,99);if(bedrooms)params.set("bedrooms",bedrooms);
const bathrooms=range(f.bathrooms,0,99);if(bathrooms)params.set("bathrooms",bathrooms);
const squareFootage=range(f.squareFootage,0,1000000);if(squareFootage)params.set("squareFootage",squareFootage);
const lotSize=range(f.lotSize,0,100000000);if(lotSize)params.set("lotSize",lotSize);
const yearBuilt=range(f.yearBuilt,1600,2100);if(yearBuilt)params.set("yearBuilt",yearBuilt);
try{const r=await fetch(`https://api.rentcast.io/v1/properties?${params.toString()}`,{headers:{"Accept":"application/json","X-Api-Key":apiKey}});const text=await r.text();let data:any=null;try{data=text?JSON.parse(text):null;}catch{data={raw:text};}if(!r.ok)return json({error:"RentCast request failed",status:r.status},r.status);let records=(Array.isArray(data)?data:[]).filter((p:any)=>num(p.lastSalePrice)&&p.lastSaleDate).filter((p:any)=>String(p.id||"")!==String(subject.id||"")&&clean(p.formattedAddress).toLowerCase()!==address.toLowerCase());const sameSubdivision=!!f.sameSubdivision;const subjectSubdivision=clean(subject.subdivision).toLowerCase();if(sameSubdivision&&subjectSubdivision)records=records.filter((p:any)=>clean(p.subdivision).toLowerCase()===subjectSubdivision);
const requestedPoolMode=["match","pool","none","any"].includes(clean(f.poolMode).toLowerCase())?clean(f.poolMode).toLowerCase():"any";const subjectPool=poolInfo(subject).hasPool;let appliedPoolMode=requestedPoolMode;if(appliedPoolMode==="match"&&subjectPool==null)appliedPoolMode="any";if(appliedPoolMode==="pool")records=records.filter((p:any)=>poolInfo(p).hasPool===true);if(appliedPoolMode==="none")records=records.filter((p:any)=>poolInfo(p).hasPool===false);if(appliedPoolMode==="match"&&subjectPool!=null)records=records.filter((p:any)=>poolInfo(p).hasPool===subjectPool);
const candidates=records.map((p:any)=>normalized(subject,p)).sort((a:any,b:any)=>b.similarityScore-a.similarityScore||((a.distanceMiles??999)-(b.distanceMiles??999))).slice(0,30);const sp=poolInfo(subject);return json({source:"RentCast Public Records",criteria:{address,radius,saleDateRange,filters:{propertyType:propertyType||null,bedrooms:bedrooms||null,bathrooms:bathrooms||null,squareFootage:squareFootage||null,lotSize:lotSize||null,yearBuilt:yearBuilt||null,sameSubdivision,poolMode:requestedPoolMode,appliedPoolMode}},subject:{id:subject.id||null,formattedAddress:address,propertyType:subject.propertyType||null,bedrooms:num(subject.bedrooms),bathrooms:num(subject.bathrooms),squareFootage:num(subject.squareFootage),lotSize:num(subject.lotSize),yearBuilt:num(subject.yearBuilt),subdivision:subject.subdivision||null,hasPool:sp.hasPool,poolType:sp.poolType,latitude:num(subject.latitude),longitude:num(subject.longitude)},candidates});}catch(e){return json({error:"Unable to reach RentCast"},502);}});
